
name: Bicep CI

on:
  push:
    paths:
      - '**.bicep'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.bicep'

jobs:
  bicep-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/setup-azure@v3

    - name: Install Bicep CLI
      run: |
        az bicep install

    - name: Lint and validate Bicep files
      run: |
        for file in $(find . -name '*.bicep'); do
          echo "Linting: $file"
          az bicep build --file "$file"
        done
