
name: Node.js App CI/CD

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run basic lint (if applicable)
      run: |
        if [ -f ".eslintrc.js" ] || [ -f ".eslintrc.json" ]; then
          npm run lint || true
        else
          echo "No ESLint config found. Skipping lint step."
        fi

    - name: Run tests (if available)
      run: |
        if [ -f "package.json" ]; then
          npm test || echo "No tests defined."
        fi

    - name: Zip the app for deployment
      run: |
        zip -r app.zip . -x '*.git*' 'node_modules/*'

    # Optional: Upload artifact
    - name: Upload app.zip artifact
      uses: actions/upload-artifact@v3
      with:
        name: nodejs-app
        path: app/app.zip

    # Optional: Deploy to Azure Web App (requires secrets)
    #- name: Deploy to Azure Web App
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
    #    slot-name: 'production'
    #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #    package: app/app.zip
